# Generated by Django 3.2.7 on 2022-06-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='rated_movies',
            field=models.IntegerField(null=True),
        ),
    ]
