# Generated by Django 3.2.12 on 2022-06-08 12:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_rated_movies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='comment_created_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='start_rating',
            new_name='star_rating',
        ),
        migrations.RenameField(
            model_name='rating',
            old_name='comment_updated_at',
            new_name='updated_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='star_created_at',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='star_updated_at',
        ),
        migrations.AddField(
            model_name='rating',
            name='dislike_users',
            field=models.ManyToManyField(related_name='dislike_ratings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='rating',
            name='like_users',
            field=models.ManyToManyField(related_name='like_ratings', to=settings.AUTH_USER_MODEL),
        ),
    ]
