# Generated by Django 3.2.7 on 2022-05-26 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0013_alter_movie_like_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='genre_ids',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
