# Generated by Django 3.2.7 on 2022-05-25 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_auto_20220525_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='movies',
            new_name='movie',
        ),
    ]
