# Generated by Django 3.2.7 on 2022-05-25 04:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0012_auto_20220525_1331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='like_users',
            field=models.ManyToManyField(related_name='rated_movies', to=settings.AUTH_USER_MODEL),
        ),
    ]
